<?php
/**
 * ROI Insights core — instantiates all components and wires up hooks.
 *
 * @package ROI_Insights
 */

/*
 * ROI Insights — Marketing Analytics & Call Tracking
 * Copyright (C) 2026 MosierData
 * License: GPL-2.0+
 */

defined( 'ABSPATH' ) || exit;

require_once ROI_INSIGHTS_DIR . 'includes/class-settings.php';
require_once ROI_INSIGHTS_DIR . 'includes/class-license.php';
require_once ROI_INSIGHTS_DIR . 'includes/class-tracking.php';
require_once ROI_INSIGHTS_DIR . 'includes/class-api.php';

class ROI_Insights {

	/** @var ROI_Insights|null */
	private static $instance = null;

	/** @var ROI_Insights_Settings */
	private $settings;

	/** @var ROI_Insights_License */
	private $license;

	/** @var ROI_Insights_Tracking */
	private $tracking;

	/** @var ROI_Insights_API */
	private $api;

	private function __construct() {
		$this->settings = new ROI_Insights_Settings();
		$this->license  = new ROI_Insights_License( $this->settings );
		$this->tracking = new ROI_Insights_Tracking( $this->settings );
		$this->api      = new ROI_Insights_API( $this->settings, $this->license );

		$this->tracking->register_hooks();
		$this->api->register_hooks();
		add_action( 'admin_menu', array( $this, 'register_admin_menu' ) );
		add_action( 'admin_enqueue_scripts', array( $this, 'enqueue_admin_assets' ) );
		add_action( 'admin_notices', array( $this, 'maybe_show_license_notice' ) );
	}

	public static function get_instance(): self {
		if ( null === self::$instance ) {
			self::$instance = new self();
		}
		return self::$instance;
	}

	// ─── Activation / Deactivation ──────────────────────────────────────────────

	public static function activate(): void {
		$settings = new ROI_Insights_Settings();
		$settings->seed_defaults();
		flush_rewrite_rules();
	}

	public static function deactivate(): void {
		flush_rewrite_rules();
	}

	// ─── Admin Menu ─────────────────────────────────────────────────────────────

	public function register_admin_menu(): void {
		add_menu_page(
			__( 'Marketing ROI', 'roi-insights' ),
			__( 'Marketing ROI', 'roi-insights' ),
			'manage_options',
			'roi-insights',
			array( $this, 'render_admin_page' ),
			'dashicons-chart-line',
			30
		);
	}

	public function render_admin_page(): void {
		// Force height/overflow reset — some security plugins inject height:100vh and overflow:hidden
		// onto arbitrary divs which clips the plugin content and prevents scrolling.
		echo '<div id="roi-insights-admin" style="height:auto!important;min-height:0!important;overflow:visible!important;"></div>';
	}

	// ─── Admin Assets ───────────────────────────────────────────────────────────

	public function enqueue_admin_assets( string $hook ): void {
		if ( 'toplevel_page_roi-insights' !== $hook ) {
			return;
		}

		$license_data = $this->license->get_license_data();

		// Load dependencies and version from the asset manifest generated by @wordpress/scripts.
		$asset_file = ROI_INSIGHTS_DIR . 'build/index.tsx.asset.php';
		$asset      = file_exists( $asset_file ) ? require $asset_file : array( 'dependencies' => array(), 'version' => ROI_INSIGHTS_VERSION );

		// jQuery is required for admin-ajax transport (XHR + X-Requested-With header).
		if ( ! in_array( 'jquery', $asset['dependencies'], true ) ) {
			$asset['dependencies'][] = 'jquery';
		}

		wp_enqueue_script(
			'roi-insights-admin',
			ROI_INSIGHTS_URL . 'build/index.tsx.js',
			$asset['dependencies'],
			$asset['version'],
			true
		);

		if ( file_exists( ROI_INSIGHTS_DIR . 'build/index.tsx.css' ) ) {
			wp_enqueue_style(
				'roi-insights-admin',
				ROI_INSIGHTS_URL . 'build/index.tsx.css',
				array(),
				$asset['version']
			);
		}

		wp_localize_script(
			'roi-insights-admin',
			'roiInsights',
			array(
				'nonce'        => wp_create_nonce( 'roi_insights_nonce' ),
				'ajaxUrl'      => admin_url( 'admin-ajax.php' ),
				'tier'         => $license_data['tier'] ?? 'free',
				'capabilities' => $license_data['capabilities'] ?? array(),
				'isValid'      => (bool) $license_data['isValid'],
				'hasKey'       => ! empty( $this->settings->get_license_key() ),
			)
		);
	}

	// ─── License Notice ─────────────────────────────────────────────────────────

	/**
	 * Show a single dismissible notice if the license key is present but invalid.
	 * Never shown if no key is configured (avoids nagging free users).
	 */
	public function maybe_show_license_notice(): void {
		$screen = get_current_screen();

		// Only show on the plugin's own page or the plugins list page.
		if ( ! $screen || ! in_array( $screen->id, array( 'toplevel_page_roi-insights', 'plugins' ), true ) ) {
			return;
		}

		$key = $this->settings->get_license_key();
		if ( empty( $key ) ) {
			return; // No key configured — no notice.
		}

		$data = $this->license->get_license_data();
		if ( $data['isValid'] ) {
			return; // Valid license — no notice.
		}

		// Key is present but invalid — show one dismissible notice.
		$dismiss_key = 'roi_insights_license_notice_dismissed';
		if ( get_user_meta( get_current_user_id(), $dismiss_key, true ) ) {
			return;
		}

		$reason_map = array(
			'api_error'         => 'Could not reach the license server. Tracking is still active.',
			'invalid_signature' => 'License signature is invalid. Please re-enter your key.',
			'expired'           => 'Your license has expired. Please renew to restore premium features.',
			'missing_key'       => '',
		);

		$reason = $reason_map[ $data['reason'] ?? '' ] ?? 'License issue detected.';
		if ( empty( $reason ) ) {
			return;
		}

		$settings_url = admin_url( 'admin.php?page=roi-insights#settings' );
		printf(
			'<div class="notice notice-warning is-dismissible"><p><strong>ROI Insights:</strong> %s <a href="%s">Go to Activation →</a></p></div>',
			esc_html( $reason ),
			esc_url( $settings_url )
		);
	}
}
